name: Descomprimir archivo tar.gz en el directorio actual

on:
  push:
    paths:
      - '**.tar.gz'  # Se activa cuando se sube un archivo tar.gz

jobs:
  descomprimir:
    runs-on: ubuntu-latest  # Usa una máquina virtual con Ubuntu
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3  # Descarga el repositorio

      - name: Descomprimir archivo tar.gz en el directorio actual
        run: tar -xzvf archivo.tar.gz  # Descomprime en el directorio actual

      - name: Eliminar archivo tar.gz (opcional)
        run: rm archivo.tar.gz  # Elimina el archivo comprimido después de descomprimir

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Archivo tar.gz descomprimido automáticamente en el directorio actual"
          git push
